version: '3'

services:
  client-nginx:
    container_name: blog-client-container
    restart: always
    image: nginx-cache-purge:1.24.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/software/client/nginx/logs:/usr/share/nginx/logs
      - /usr/software/client/nginx/html:/usr/share/nginx/html
      - /usr/software/client/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/software/acme.sh:/usr/share/nginx/acme.sh
    command: nginx -g "daemon off;"

  manage-nginx:
    container_name: blog-manage-container
    restart: always
    image: nginx-cache-purge:1.24.0
    ports:
      - "233:233"
    volumes:
      - /usr/software/manage/nginx/logs:/usr/share/nginx/logs
      - /usr/software/manage/nginx/html:/usr/share/nginx/html
      - /usr/software/manage/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/software/acme.sh:/usr/share/nginx/acme.sh
    command: nginx -g "daemon off;"

  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    restart: always
    network_mode: host
    volumes:
      - /usr/software/acme.sh:/home/ssl
    command: daemon
    environment:
      DP_Id: 460928
      DP_Key: d1dd3a8ca62a162f2125e8f553c3309e
      TZ: Asia/Shanghai