/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomUpload: typeof import('./src/components/custom-upload/CustomUpload.vue')['default']
    DataTable: typeof import('./src/common/data-table/DataTable.vue')['default']
    DeleteLink: typeof import('./src/components/modal-operation/DeleteLink.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElText: typeof import('element-plus/es')['ElText']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmojiExtension: typeof import('./src/components/markdown/emoji-extension/EmojiExtension.vue')['default']
    FutureWeather: typeof import('./src/common/future-weather/FutureWeather.vue')['default']
    MarkExtension: typeof import('./src/components/markdown/mark-extension/MarkExtension.vue')['default']
    ModalDelete: typeof import('./src/components/modal-operation/ModalDelete.vue')['default']
    ModalModify: typeof import('./src/components/modal-operation/ModalModify.vue')['default']
    RoseChart: typeof import('./src/common/rose-chart/RoseChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableSearch: typeof import('./src/components/table-search/TableSearch.vue')['default']
    TimeNow: typeof import('./src/components/markdown/time-now/TimeNow.vue')['default']
    UserUpload: typeof import('./src/components/user-upload/UserUpload.vue')['default']
  }
}
