/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Inlet: typeof import('./src/components/Inlet.vue')['default']
    LayoutHeader: typeof import('./src/components/layout-header/LayoutHeader.vue')['default']
    LayoutHeaderAction: typeof import('./src/components/layout-header/LayoutHeaderAction.vue')['default']
    LayoutHeaderBreadcrumb: typeof import('./src/components/layout-header/LayoutHeaderBreadcrumb.vue')['default']
    LayoutHeaderPageOperation: typeof import('./src/components/layout-header/LayoutHeaderPageOperation.vue')['default']
    LayoutHeaderRouterList: typeof import('./src/components/layout-header/LayoutHeaderRouterList.vue')['default']
    LayoutSider: typeof import('./src/components/layout-sider/LayoutSider.vue')['default']
    LayoutSiderPc: typeof import('./src/components/layout-sider/LayoutSiderPc.vue')['default']
    LayoutSiderPhone: typeof import('./src/components/layout-sider/LayoutSiderPhone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
