/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./../src/views/login/modules/Account.vue')['default']
    BlogArticle: typeof import('./../src/views/blog/article/Index.vue')['default']
    BlogArticles: typeof import('./../src/views/blog/articles/Index.vue')['default']
    BlogCategroy: typeof import('./../src/views/blog/categroy/Index.vue')['default']
    BlogCategroys: typeof import('./../src/views/blog/categroys/Index.vue')['default']
    BlogFeeling: typeof import('./../src/views/blog/feeling/Index.vue')['default']
    BlogFeelings: typeof import('./../src/views/blog/feelings/Index.vue')['default']
    BlogTag: typeof import('./../src/views/blog/tag/Index.vue')['default']
    BlogTags: typeof import('./../src/views/blog/tags/Index.vue')['default']
    Header: typeof import('./../src/layout/header/Index.vue')['default']
    Home: typeof import('./../src/views/home/Index.vue')['default']
    Index: typeof import('./../src/layout/Index.vue')['default']
    Login: typeof import('./../src/views/login/Index.vue')['default']
    LoginModulesAccount: typeof import('./../src/views/login/modules/Account.vue')['default']
    LoginModulesPhone: typeof import('./../src/views/login/modules/Phone.vue')['default']
    Main: typeof import('./../src/layout/main/Index.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    Phone: typeof import('./../src/views/login/modules/Phone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Silder: typeof import('./../src/layout/silder/Index.vue')['default']
    SquareJellyBox: typeof import('./../src/common/square-jelly-box/Index.vue')['default']
    SystemLogging: typeof import('./../src/views/system/logging/Index.vue')['default']
    SystemLoginLogs: typeof import('./../src/views/system/login-logs/Index.vue')['default']
    SystemNotice: typeof import('./../src/views/system/notice/Index.vue')['default']
    SystemPersonage: typeof import('./../src/views/system/personage/Index.vue')['default']
    SystemTimingLogs: typeof import('./../src/views/system/timing-logs/Index.vue')['default']
  }
}
