server:
  port: 7777
# hikari
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 15
      max-lifetime: 1200000
      idle-timeout: 300000
      auto-commit: true
    type: com.zaxxer.hikari.HikariDataSource
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(9xj68zX/D2S9nBiwbOkA1Mcl3teKZzHi9RNQhL68V/Sc2+gxtOaX1H4VH+AVJSgqkyTwJjNo5RGa7+vPExP/CnfPZtBt9hnebFuu5kLj4/aRcRKIDDhv4cjheOZWcGhms2igAF+pcDrIaNPvgWsNMN7it8oifb6C64+t4RAmp+d6o+7Kco/6QOORNj9BLAv+UJc+CcHEYmJ8gFfZalJdAF5zy7El7a0a7ZrwTSWzteDwt+nKiuWy3fxBaXfRCv2P5g+53x3r/AyiWV1pB87kAQ==)
    username: ENC(NO9M2/eS74LT9NYKHtv2IkMUgik6oSdZ1cEoRyk+0IhLEDhzdaKlQ+SOVsKASqhj)
    password: ENC(5/hUuCq3DHBDRTiTsSuOqG97V3B9dGHw4SKLDPU6PgW6aIXyHQpWjXaz77SuLWOd)
  # redis
  data:
    redis:
      ## 链接主机地址
      host: ENC(uYwS37UAlz9O2VcyB1Ev2ot39KMcgNZHC93VnCObliI9lvYz8EKZ/Hb8TV5MAlXF)
      ## 链接端口号
      port: ENC(e4tecihifZhyS5ku/uvuMaXRxP1pfhDoAxxR6sX4spAckthgRYF4jJmNZ/b1IMCk)
      ## redis库，有16个
      database: ENC(6FYaS0jj5MLAmWqTEhIkND8EjJ4KQStaokjX8/oNuvO8rlIgjA8e7aNRuXrRtSir)
      ## redis密码
      password: ENC(wRhhsqtgAnecLJWwm0fJRrYyjVdoTF0Xi2MXFHW6z12e7O4wixyRsxM+vv6MOlvu)
      ## 超时时间6s
      timeout: 6000
      ## 没有超时时间
      jedis:
        pool:
          ## 最小的空闲的线程数
          min-idle: 2
          ## 最大的空闲的线程数
          max-idle: 10
          ## 最大激活的线程数
          max-active: 8
          max-wait: -1
# mybatis-plus
mybatis-plus:
  type-aliases-package: com.tanx.blog.entity.po
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: enable
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  swagger-ui:
    path: /index.html
    #当 persistAuthorization 参数设置为 true 时，客户端会将授权信息保存在本地存储中，以便在下次访问时自动使用该授权信息。
    #如果设置为 false，则客户端不会保存授权信息，需要在每次访问时重新进行授权。
    persistAuthorization: false
    # 根据HTTP对路径进行排序
    operationsSorter: method